disabled_rules:
 - identifier_name #short vars
 - type_body_length
 - statement_position #}else{
 - attributes
 - nesting #?
 - todo #todo
 - file_length
 - function_body_length
 - trailing_whitespace #xcode default
 - cyclomatic_complexity
 - pattern_matching_keywords #hz
 - override_in_extension #hz
 - trailing_comma
 - inclusive_language
 - redundant_nil_coalescing #intruduces bugs
 
 - function_parameter_count #?
 - multiple_closures_with_trailing_closure
 - is_disjoint #?
 - no_fallthrough_only #?
 - notification_center_detachment
 - redundant_string_enum_value
 - legacy_hashing
 - comment_spacing
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - explicit_init
  - first_where
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - nimble_operator
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - unneeded_parentheses_in_closure_argument
  - brackets_statment
  - closure_inner_space
  - brackets_space
excluded:
 - Pods
 - .build
 - LinuxMain.swift
 - spark-core/LinuxMain.swift
 - "**/Pods"
 - spark-database/SparkDatabaseTests
 - spark-composer/SparkComposerTests
 - spark-body-parser/SmartMailMessageParserTests
 - spark-common/SmartMailCommonTests
 - spark-searchContacts/SearchContactsTests
 - spark-searchContacts/SearchContactsOSXTests
 - spark-database/SparkDatabase
 - spark-database/SparkDatabaseOSXTests

type_name:
  min_length: 1 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
identifier_name:
  min_length: # only min_length
    error: 1 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
line_length: 1000 #160
number_separator:
  minimum_length: 5
custom_rules:
  brackets_statment:
   name: Brackets Statment
   message: statments after } shoule be started from new line
   regex: \}[ ]*(if|else|catch)
   severity: error
  brackets_space:
    name: Block Opening
    message: shoule be whitespace after {
    regex: \{(?:\(|\w)
    severity: error
    match_kinds: # SyntaxKinds to match. optional.
         - parameter
         - identifier
  closure_inner_space:
   name: Closure Inner Space
   message: closures should have space after {
   regex: \{\w+(?:, \w+)* in\b
   severity: warning
   
   #TODO todo should have tickect refrence
